---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhtas-image-signing
  labels:
    app: rhtas-image-test
spec:
  selector:
    matchLabels:
      app: name
  replicas: 1
  template:
    metadata:
      labels:
        app: name
    spec:
      containers:
        - name: container
          image: tas-httpd
          ports:
            - containerPort: 8080
              protocol: TCP
