apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
namespace: pa-rhtas-test
images:
  - name: tas-httpd
    newName: quay.io/pabrahamsson/tas-httpd
    newTag: signed
